import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  test.skip(!await page.getByText('演示模式', { exact: true }).isVisible(), '需要演示模式')
})

test('时间轴与事件同步缩放，支持边界、重置、视图切换和持久化', async ({ page }) => {
  await page.getByRole('button', { name: /添加日程|新建日程/ }).first().click()
  await page.locator('#ev-title').fill('缩放验证')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const card = page.locator('.chronos-event-card').filter({ hasText: '缩放验证' })
  await expect(card).toBeAttached()
  const original = (await card.boundingBox())!.height
  const hour = page.locator('[data-time="09:00:00"]').last()
  const height = () => hour.evaluate((element) => element.getBoundingClientRect().height)
  await expect.poll(height).toBe(64)
  await page.getByRole('button', { name: '放大时间表' }).click()
  await expect.poll(height).toBe(80)
  await expect.poll(async () => (await card.boundingBox())!.height).toBeGreaterThan(original)
  await page.reload()
  await expect(page.getByRole('slider', { name: '时间表缩放比例' })).toHaveValue('125')
  await expect.poll(height).toBe(80)
  for (let index = 0; index < 3; index++) await page.getByRole('button', { name: '放大时间表' }).click()
  await expect.poll(height).toBe(128)
  await expect(page.getByRole('button', { name: '放大时间表' })).toBeDisabled()
  for (let index = 0; index < 6; index++) await page.getByRole('button', { name: '缩小时间表' }).click()
  await expect.poll(height).toBe(32)
  await expect(page.getByRole('button', { name: '缩小时间表' })).toBeDisabled()
  await page.getByRole('slider', { name: '时间表缩放比例' }).fill('150')
  await expect.poll(height).toBe(96)
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.getByRole('slider')).toHaveCount(1)
  await page.getByRole('button', { name: '日', exact: true }).click()
  await expect(page.getByRole('slider')).toHaveValue('150')
  await page.getByRole('button', { name: '重置时间表缩放' }).click()
  await expect.poll(height).toBe(64)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('空分类账号可通过基础类型创建日程，主题色修改会更新日程并保存', async ({ page }) => {
  await page.evaluate(() => localStorage.setItem('chronos.demo.v1', JSON.stringify({ categories: [], events: [] })))
  await page.reload()
  await page.getByRole('button', { name: /添加日程|新建日程/ }).first().click()
  await page.locator('#ev-title').fill('工作类型验证')
  await page.getByRole('checkbox', { name: '全天事件' }).check()
  await page.getByRole('group', { name: '基础任务类型', exact: true }).getByRole('button', { name: '工作', exact: true }).click()
  await expect(page.locator('#ev-cat option:checked')).toHaveText('工作')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const card = page.locator('.chronos-event-card').filter({ hasText: '工作类型验证' })
  await expect(card).toHaveCSS('border-left-color', 'rgb(79, 70, 229)')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('dialog').getByText('修改主题色', { exact: true }).click()
  await page.getByRole('button', { name: '工作 的颜色：玫瑰', exact: true }).click()
  await expect(page.getByRole('button', { name: '工作 的颜色：玫瑰', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(card).toHaveCSS('border-left-color', 'rgb(219, 39, 119)')
  await page.reload()
  await expect(card).toHaveCSS('border-left-color', 'rgb(219, 39, 119)')
  await card.click()
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(page.locator('#ev-cat option:checked')).toHaveText('工作')
})

test('自定义类型支持主题色和自由选色，已有类型不会重复添加', async ({ page }) => {
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('textbox', { name: '新分类名称', exact: true }).fill('阅读')
  await page.getByRole('button', { name: '新分类颜色：天青', exact: true }).click()
  await expect(page.getByLabel('新分类颜色：自定义颜色', { exact: true })).toHaveValue('#0891b2')
  await page.getByLabel('新分类颜色：自定义颜色', { exact: true }).fill('#123abc')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '阅读 的名称', exact: true })).toBeVisible()
  const reading = page.getByRole('listitem').filter({ has: page.getByRole('textbox', { name: '阅读 的名称', exact: true }) })
  await reading.getByText('修改主题色', { exact: true }).click()
  await expect(page.getByLabel('阅读 的颜色：自定义颜色', { exact: true })).toHaveValue('#123abc')
  await expect(page.getByRole('group', { name: '添加基础任务类型', exact: true }).getByRole('button', { name: '课程 ✓' })).toBeDisabled()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: /添加日程|新建日程/ }).first().click()
  await expect(page.locator('#ev-cat option').filter({ hasText: '阅读' })).toHaveCount(1)
})
