import { expect, test, type Page } from '@playwright/test'

async function clickTime(page: Page, time: string, offset = 5) {
  const box = (await page.locator(`[data-time="${time}:00"]`).last().boundingBox())!
  // 时间网格上方有负责交互的透明日期层，用实际坐标模拟点击/轻触。
  const x = box.x + 60, y = box.y + offset
  if (test.info().project.name === 'mobile-chrome') await page.touchscreen.tap(x, y)
  else await page.mouse.click(x, y)
}

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('chronos.demo.v1')) localStorage.setItem('chronos.demo.v1', JSON.stringify({ categories: [], events: [] }))
  })
  await page.goto('/')
  test.skip(!await page.getByText('演示模式', { exact: true }).isVisible(), '需要演示模式')
})

test('视图按年、月、周、日排列，年视图展示十二个月，切换保留缩放', async ({ page }) => {
  await expect(page.getByRole('group', { name: '日历视图' }).getByRole('button')).toHaveText(['年', '月', '周', '日'])
  await page.getByRole('slider').fill('125')
  await page.getByRole('button', { name: '年', exact: true }).click()
  await expect(page.getByRole('button', { name: '年', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.chronos-year-month')).toHaveCount(12)
  await expect(page.getByRole('slider')).toHaveValue('125')
  await page.getByRole('button', { name: '下一段', exact: true }).click()
  const nextYear = String(new Date().getFullYear() + 1)
  await expect(page.locator('h1')).toHaveText(`${nextYear}年`)
  await page.getByRole('button', { name: '今天', exact: true }).first().click()
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.locator('.chronos-month-cell')).not.toHaveCount(0)
  await page.getByRole('button', { name: '周', exact: true }).click()
  await expect(page.locator('.chronos-date-number')).toHaveCount(7)
  await page.getByRole('button', { name: '日', exact: true }).click()
  await expect(page.locator('.chronos-date-number')).toHaveCount(1)
})

test('空白时段先选中，再点击选区才打开表单；改变时段与切换视图可清除选区', async ({ page }) => {
  await page.getByRole('button', { name: '日', exact: true }).click()
  await clickTime(page, '10:00')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText(/再次点击选中区域创建日程/)).toBeVisible()
  await clickTime(page, '10:00', 25)
  await expect(page.getByRole('dialog', { name: '新建日程' })).toBeVisible()
  await expect(page.locator('#ev-st')).toHaveValue('10:00')
  await expect(page.locator('#ev-et')).toHaveValue('11:00')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await clickTime(page, '10:00')
  await clickTime(page, '11:00')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText(/已选中.*11:00/)).toBeVisible()
  await page.getByRole('button', { name: '周', exact: true }).click()
  await expect(page.getByText(/再次点击选中区域创建日程/)).toHaveCount(0)
})

test('拖选完成后保留范围，再点击范围内任意位置创建', async ({ page, isMobile }) => {
  test.skip(isMobile, '鼠标拖选；触屏点选由两步创建用例覆盖')
  await page.getByRole('button', { name: '日', exact: true }).click()
  const box = (await page.locator('[data-time="10:00:00"]').last().boundingBox())!
  await page.mouse.move(box.x + 60, box.y + 2)
  await page.mouse.down()
  await page.mouse.move(box.x + 60, box.y + 80, { steps: 12 })
  await page.mouse.up()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText(/再次点击选中区域创建日程/)).toBeVisible()
  await clickTime(page, '10:00', 35)
  await expect(page.getByRole('dialog', { name: '新建日程' })).toBeVisible()
  await expect(page.locator('#ev-st')).toHaveValue('10:00')
  await expect(page.locator('#ev-et')).toHaveValue('11:15')
})

test('月视图先选日期再创建全天日程，Esc 取消选区', async ({ page }) => {
  await page.getByRole('button', { name: '月', exact: true }).click()
  await page.getByRole('slider').fill('200')
  const today = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Shanghai' })
  const cell = page.locator(`.chronos-month-cell[data-date="${today}"]`)
  await cell.click({ position: { x: 12, y: 40 } })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText(/再次点击选中区域创建日程/)).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByText(/再次点击选中区域创建日程/)).toHaveCount(0)
  await cell.click({ position: { x: 12, y: 40 } })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await cell.click({ position: { x: 12, y: 40 } })
  await expect(page.getByRole('dialog', { name: '新建日程' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: '全天事件' })).toBeChecked()
  await expect(page.locator('#ev-sd')).toHaveValue(today)
})

test('年视图日期支持两步创建，动画尊重系统减少动态效果设置', async ({ page }) => {
  await page.getByRole('button', { name: '年', exact: true }).click()
  await expect.poll(() => page.locator('.chronos-calendar-surface').evaluate(el => el.getAnimations().some(a => a.playState === 'running'))).toBe(true)
  const today = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Shanghai' })
  const cell = page.locator(`.chronos-year-month [role="gridcell"][data-date="${today}"]`)
  await cell.click({ position: { x: 10, y: 25 } })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText(/再次点击选中区域创建日程/)).toBeVisible()
  await cell.click({ position: { x: 10, y: 25 } })
  await expect(page.getByRole('dialog', { name: '新建日程' })).toBeVisible()
  await expect(page.locator('#ev-sd')).toHaveValue(today)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.getByRole('button', { name: '月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(() => page.locator('.chronos-calendar-surface').evaluate(el => el.getAnimations().some(a => a.playState === 'running'))).toBe(false)
})

test('每条日程独立选择提醒，新建默认不提醒，编辑和刷新保持选择', async ({ page }) => {
  await page.getByRole('button', { name: '日', exact: true }).click()
  await page.getByRole('button', { name: /添加日程|新建日程/ }).first().click()
  await expect(page.getByRole('checkbox', { name: '此日程系统提醒' })).not.toBeChecked()
  await page.locator('#ev-title').fill('单独提醒测试')
  await page.getByRole('checkbox', { name: '此日程系统提醒' }).check()
  await page.getByLabel('此日程提前提醒时间').selectOption('0')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: '日', exact: true }).click()
  await page.locator('.chronos-event-card').filter({ hasText: '单独提醒测试' }).click()
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: '此日程系统提醒' })).toBeChecked()
  await expect(page.getByLabel('此日程提前提醒时间')).toHaveValue('0')
  await page.getByRole('checkbox', { name: '此日程系统提醒' }).uncheck()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await page.getByRole('button', { name: /添加日程|新建日程/ }).first().click()
  await expect(page.getByRole('checkbox', { name: '此日程系统提醒' })).not.toBeChecked()
})
